// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GoToRecentFile
{
    internal sealed partial class Vsix
    {
        public const string Id = "GoToRecentFile.dc380116-29c9-4190-bd19-434954fded50";
        public const string Name = "GoToRecentFile";
        public const string Description = @"Alternative for GoToRecentFile in Visual Studio IDE.";
        public const string Language = "en-US";
        public const string Version = "2026.1.0.1";
        public const string Author = "Lokesh Govindu";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
